version: '3.8'

services:
   db:
      image: postgres:latest
      environment:
         POSTGRES_USER: ${POSTGRES_USER}
         POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
         POSTGRES_DB: ${POSTGRES_DB}
      ports:
         - "${DB_PORT}:${POSTGRES_PORT}"
      restart: always

   backend:
      build: ./back
      environment:
         DATABASE_URL: ${DATABASE_URL}
         JWT_SECRET: ${JWT_SECRET}
         API_PORT: ${API_PORT}
      ports:
         - "${API_PORT}:${API_PORT}"
      depends_on:
         - db
      volumes:
         - ./back:/app
      command: sh -c "sleep 5 && npm start"
      restart: always

